args = commandArgs(trailingOnly=TRUE)
pname = as.character(args[1])
print("reading summmary files...")
sumstat <- read.table(paste0("/dcl01/chatterj/data/jzhang2/pwas/pipeline/Results_GRCh38/Black/pQTL/fine-mapping/summary_stat/",pname,".PHENO1.glm.linear"),header = F)
af <- read.table(paste0("/dcl01/chatterj/data/jzhang2/pwas/pipeline/Results_GRCh38/Black/pQTL/fine-mapping/summary_stat/",pname,".afreq"),header = T)
n.snp <- nrow(sumstat)
ss <- data.frame(sumstat[,c(1:3)],sumstat$V9/sumstat$V10)
ld <- readBin(paste0("/dcl01/chatterj/data/jzhang2/pwas/pipeline/Results_GRCh38/Black/pQTL/fine-mapping/LD/",pname,".ld.bin"), what="numeric", size=4, n=(n.snp)^2)
ld = matrix(ld,ncol = n.snp,byrow = T)
library(susieR)
print("eigen decomposition of LD....")
e1 = eigen(ld); ev <- e1$values; ev[ev < 0] = 0; R1 = e1$vectors%*%diag(ev)%*%t(e1$vectors)
print("Running SusiE....")
system.time(fitted_rss <- susie_rss(ss$sumstat.V9.sumstat.V10, R = R1, L = 10,estimate_residual_variance = TRUE,estimate_prior_variance = TRUE,verbose = TRUE))
system(paste0("mkdir -p /dcl01/chatterj/data/diptavo/pQTL/susie/",pname))
system(paste0("mkdir -p /dcl01/chatterj/data/diptavo/pQTL/susie/",pname,"/Black/"))
saveRDS(object = list(ss,af,fitted_rss) ,paste0("/dcl01/chatterj/data/diptavo/pQTL/susie/",pname,"/Black/susie_10.rds"))
